version: "3.9"
services:
  main-bot:
    container_name: main-bot
    build: .
    environment:
        CONFIG_FOLDER: "/etc/buildtheearth/main-bot/config"
    volumes:
      - "${CONFIG_FOLDER}:/etc/buildtheearth/main-bot/config"
