version: "3.9"

services:
  main-bot:
    container_name: main-bot
    build: .
    networks:
      - bot-network
    environment:
        CONFIG_FOLDER: "/etc/buildtheearth/main-bot/config"
    volumes:
      - "${CONFIG_FOLDER}:/etc/buildtheearth/main-bot/config"
      
networks:
  bot-network:
    external: true
