version: '1'
services:
  main-bot-service:
    image: buildtheearth/main-bot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-bot
    volumes:
      - type: bind
        source: ./config
        target: /home/bots/main-bot/config
