SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `temporary_blunder_tracker` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `description` varchar(255) NOT NULL, `role` varchar(19), `last_blunder` date, `message` varchar(19) NOT NULL, `channel` varchar(19) NOT NULL);
INSERT INTO `temporary_blunder_tracker`(`id`, `description`, `role`, `last_blunder`, `message`, `channel`) SELECT `id`, `description`, `role`, `last_blunder`, `message`, `channel` FROM `blunder_tracker`;
DROP TABLE `blunder_tracker`;
ALTER TABLE `temporary_blunder_tracker` RENAME TO `blunder_tracker`;
CREATE TABLE `temporary_suggestions` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `number` integer, `extends` integer, `author` varchar(19) NOT NULL, `anonymous` boolean NOT NULL, `title` varchar(255) NOT NULL, `body` varchar(2048) NOT NULL, `teams` varchar(255), `status` varchar(255), `status_updater` varchar(19), `status_reason` varchar(1024), `message` varchar(19) NOT NULL, `thread` varchar(19), `staff` boolean NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `deleted_at` datetime, `deleter` varchar(19));
INSERT INTO `temporary_suggestions`(`id`, `number`, `extends`, `author`, `anonymous`, `title`, `body`, `teams`, `status`, `status_updater`, `status_reason`, `message`, `thread`, `staff`, `created_at`, `deleted_at`, `deleter`) SELECT `id`, `number`, `extends`, `author`, `anonymous`, `title`, `body`, `teams`, `status`, `status_updater`, `status_reason`, `message`, `thread`, `staff`, `created_at`, `deleted_at`, `deleter` FROM `suggestions`;
DROP TABLE `suggestions`;
ALTER TABLE `temporary_suggestions` RENAME TO `suggestions`;
CREATE TABLE `temporary_tasks` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `title` varchar(255) NOT NULL, `description` varchar(2048) NOT NULL, `creator` varchar(19) NOT NULL, `assignees` text NOT NULL, `status` varchar(255));
INSERT INTO `temporary_tasks`(`id`, `title`, `description`, `creator`, `assignees`, `status`) SELECT `id`, `title`, `description`, `creator`, `assignees`, `status` FROM `tasks`;
DROP TABLE `tasks`;
ALTER TABLE `temporary_tasks` RENAME TO `tasks`;
CREATE TABLE `temporary_moderation_notes` (`member` varchar(19) PRIMARY KEY NOT NULL, `body` varchar(1024) NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updaters` text NOT NULL);
INSERT INTO `temporary_moderation_notes`(`member`, `body`, `created_at`, `updated_at`, `updaters`) SELECT `member`, `body`, `created_at`, `updated_at`, `updaters` FROM `moderation_notes`;
DROP TABLE `moderation_notes`;
ALTER TABLE `temporary_moderation_notes` RENAME TO `moderation_notes`;
CREATE TABLE `temporary_banned_words` (`word` varchar(19) PRIMARY KEY NOT NULL, `punishment_type` varchar(255), `reason` varchar(1024), `duration` integer, `exception` boolean NOT NULL DEFAULT (0));
INSERT INTO `temporary_banned_words`(`word`, `punishment_type`, `reason`, `duration`, `exception`) SELECT `word`, `punishment_type`, `reason`, `duration`, `exception` FROM `banned_words`;
DROP TABLE `banned_words`;
ALTER TABLE `temporary_banned_words` RENAME TO `banned_words`;
CREATE TABLE `temporary_teampoint_permissions` (`roleId` varchar(19) PRIMARY KEY NOT NULL, `maxPoints` float NOT NULL DEFAULT (0), `minPoints` float NOT NULL DEFAULT (0), `maxUsagesPerDay` integer NOT NULL DEFAULT (10));
INSERT INTO `temporary_teampoint_permissions`(`roleId`, `maxPoints`, `minPoints`, `maxUsagesPerDay`) SELECT `roleId`, `maxPoints`, `minPoints`, `maxUsagesPerDay` FROM `teampoint_permissions`;
DROP TABLE `teampoint_permissions`;
ALTER TABLE `temporary_teampoint_permissions` RENAME TO `teampoint_permissions`;
CREATE TABLE `temporary_suspicious_users` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `userId` varchar(19) NOT NULL, `submitterId` varchar(19) NOT NULL, `messageId` varchar(19) NOT NULL, `denied` boolean NOT NULL DEFAULT (0), `approved` boolean NOT NULL DEFAULT (0), `moderatorId` varchar(19), `reason` text, `evidence` text NOT NULL, `deletedAt` datetime, `threadId` varchar(19));
INSERT INTO `temporary_suspicious_users`(`id`, `userId`, `submitterId`, `messageId`, `denied`, `approved`, `moderatorId`, `reason`, `evidence`, `deletedAt`, `threadId`) SELECT `id`, `userId`, `submitterId`, `messageId`, `denied`, `approved`, `moderatorId`, `reason`, `evidence`, `deletedAt`, `threadId` FROM `suspicious_users`;
DROP TABLE `suspicious_users`;
ALTER TABLE `temporary_suspicious_users` RENAME TO `suspicious_users`;
CREATE TABLE `temporary_advanced_builders` (`builder` varchar(19) PRIMARY KEY NOT NULL, `given_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `role_name` varchar(255) NOT NULL DEFAULT ('ADVANCED_BUILDER'));
INSERT INTO `temporary_advanced_builders`(`builder`, `given_at`, `role_name`) SELECT `builder`, `given_at`, `role_name` FROM `advanced_builders`;
DROP TABLE `advanced_builders`;
ALTER TABLE `temporary_advanced_builders` RENAME TO `advanced_builders`;
CREATE TABLE `temporary_teampoint_users` (`userId` varchar(19) PRIMARY KEY NOT NULL, `commandUsagesToday` integer NOT NULL DEFAULT (0));
INSERT INTO `temporary_teampoint_users`(`userId`, `commandUsagesToday`) SELECT `userId`, `commandUsagesToday` FROM `teampoint_users`;
DROP TABLE `teampoint_users`;
ALTER TABLE `temporary_teampoint_users` RENAME TO `teampoint_users`;
CREATE TABLE `temporary_timed_punishments` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `member` varchar(19) NOT NULL, `type` varchar(255) NOT NULL, `length` integer NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO `temporary_timed_punishments`(`id`, `member`, `type`, `length`, `created_at`) SELECT `id`, `member`, `type`, `length`, `created_at` FROM `timed_punishments`;
DROP TABLE `timed_punishments`;
ALTER TABLE `temporary_timed_punishments` RENAME TO `timed_punishments`;
CREATE TABLE `temporary_reminders` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `channel` varchar(19) NOT NULL, `message` varchar(1024) NOT NULL, `interval` varchar(255) NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `next_fire_date` integer NOT NULL);
INSERT INTO `temporary_reminders`(`id`, `channel`, `message`, `interval`, `created_at`, `next_fire_date`) SELECT `id`, `channel`, `message`, `interval`, `created_at`, `next_fire_date` FROM `reminders`;
DROP TABLE `reminders`;
ALTER TABLE `temporary_reminders` RENAME TO `reminders`;
CREATE TABLE `temporary_action_logs` (`id` integer PRIMARY KEY AUTO_INCREMENT NOT NULL, `action` varchar(255) NOT NULL, `member` varchar(19) NOT NULL, `executor` varchar(19) NOT NULL, `reason` varchar(1024) NOT NULL, `reason_image` varchar(255), `length` integer, `channel` varchar(19) NOT NULL, `message` varchar(19) NOT NULL, `notification` varchar(19), `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `deleted_at` datetime, `deleter` varchar(19), `delete_reason` varchar(1024), `punishment_id` integer, CONSTRAINT `REL_1b2ce2a6f60a2cea07c0c73e9a` UNIQUE (`punishment_id`), CONSTRAINT `FK_1b2ce2a6f60a2cea07c0c73e9a0_1` FOREIGN KEY (`punishment_id`) REFERENCES `timed_punishments` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION);
INSERT INTO `temporary_action_logs`(`id`, `action`, `member`, `executor`, `reason`, `reason_image`, `length`, `channel`, `message`, `notification`, `created_at`, `deleted_at`, `deleter`, `delete_reason`, `punishment_id`) SELECT `id`, `action`, `member`, `executor`, `reason`, `reason_image`, `length`, `channel`, `message`, `notification`, `created_at`, `deleted_at`, `deleter`, `delete_reason`, `punishment_id` FROM `action_logs`;
DROP TABLE `action_logs`;
ALTER TABLE `temporary_action_logs` RENAME TO `action_logs`;
CREATE TABLE `temporary_moderation_menus` (`member` varchar(19) PRIMARY KEY NOT NULL, `message` varchar(19) NOT NULL, `message_text` varchar(2000) NOT NULL, `punishments` text NOT NULL, `offenses` integer NOT NULL, `current_word` varchar(255) NOT NULL);
INSERT INTO `temporary_moderation_menus`(`member`, `message`, `message_text`, `punishments`, `offenses`, `current_word`) SELECT `member`, `message`, `message_text`, `punishments`, `offenses`, `current_word` FROM `moderation_menus`;
DROP TABLE `moderation_menus`;
ALTER TABLE `temporary_moderation_menus` RENAME TO `moderation_menus`;
SET FOREIGN_KEY_CHECKS=1;