#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Builder can be found at 'npm start cm'"
echo "Builder can be found at 'npm start cm'"
echo "Builder can be found at 'npm start cm'"
npm start pre-commit
