name: Build
on:
    push:
    pull_request:
jobs:
    tsc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: npm i
            - run: npm start build
